### ISSUE TITLE
Bug: PHP client - Logout issue

### ISSUE THREAD

**Issue by blanchonvincent** [FusionAuth/fusionauth-issues#27]
**Describe the bug**
The PHP client has an issue on the logout.
There is no test in `FusionAuthClientTest` for that ^^

**To Reproduce**
From PHP client
```php
$response = $auth->logout("true", $refreshToken);
```

I get:

```
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
</body>
</html>
```

via cURL in CLI:

```
curl -X POST -H "Authorization: XXXXXXXXXX" "https://myfusionauth/api/logout?global=true&refreshToken=XXXXX" -vvv
```

I get a code 200.

Also the documentation says that `$global` should be an array when it should be a boolean.
Also if we could make the second argument as optional in order to make this example working

```php
$response = $auth->logout(true);
```

**Comment by voidmain** [comment]
It looks like this is a bug in our tool that builds the client libraries. It was missing a conversion between Java boolean type to the PHP boolean type.

As for the second argument, it is optional, so you can just pass `NULL` for now. I updated the code to set a default value for optional parameters in PHP. This should fix the problem of having to pass in `NULL`. 

All of this should be ready early next week when we release version `1.1.0`.

**Comment by voidmain** [comment]
This fix has been released and is now available. Open a new issue if you see any problems in the PHP client.

Fixed by this commit:
https://github.com/FusionAuth/fusionauth-php-client/commit/61fcd3aa01c0e7f11ca36c9a5b90b017ee653513

**Comment by blanchonvincent** [comment]
`$response = $auth->logout(false, $refreshToken);`

the URL called is `string(116) "https://auth.x.mycrm.com/api/logout?global=false&refreshToken=hepDFnXbGCawKdSECShBAEaVQTD3CkhMKFI14mE2lVUtUBvAv9lm4g"`

but still receive a 400 error code

```
string(138) "<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
</body>
</html>
```

but when I try with cURL it works

```
curl -X POST -H "Authorization: XXXXXXXX" 'https://auth.x.mycrm.com/api/logout?global=true&refreshToken=XXXXX' -vvv
```

```
> POST /api/logout?global=true&refreshToken=XXXXXX HTTP/1.1
> User-Agent: curl/7.29.0
> Host: auth.x.mycrm.com
> Accept: */*
> Authorization: XXXXXX
>
< HTTP/1.1 200
```

**Comment by robotdan** [comment]
Hi @blanchonvincent sorry this has gotten buried under the pile. :-) 

Is this still an issue that we need to look at or can it be closed?
